version: "3.1"

services:
  db:
    container_name: mysql
    image: mysql:8.0.27
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-authentication-plugin=mysql_native_password"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      TZ: Asia/Tokyo
    volumes:
      - ./.data/db:/var/lib/mysql
      - ./log:/var/log/mysql
