version: "3.1"

services:
  db:
    container_name: mysql
    image: mysql:8.0.27
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      TZ: Asia/Tokyo
    volumes:
      - ./build/package/my.cnf:/etc/my.cnf
      - ./.data/db:/var/lib/mysql
      - ./log:/var/log/mysql
